# Generated by Django 4.1 on 2022-12-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, default='author-imgs\\Default Image.jpg', null=True, upload_to='author-imgs'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, default='book_imgs\\Default Book.jpg', null=True, upload_to='book_imgs'),
        ),
    ]
